/* SQLBootcamp.online */

USE master
GO 

-- Check current date
SELECT GETDATE();

-- Apply DATEDIFF function on any 
-- of the dates generated by the queries below

-- DATEDIFF( interval, startdate, enddate)
-- Intervals: hour, day, month, etc


-- Check SQL uptime Method 1
SELECT DATEDIFF(minute,[create_date],GETDATE())
FROM sys.databases 
WHERE [name] = 'tempDB';

-- Check SQL uptime Method 2
SELECT DATEDIFF(month,[login_time],GETDATE())
FROM sys.sysprocesses 
WHERE [spid] = 1;

-- Check SQL uptime Method 3
SELECT 
DATEDIFF(hour,[sqlserver_start_time],GETDATE())
FROM sys.dm_os_sys_info;
